# Generated by Django 5.1.6 on 2025-02-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(max_length=50)),
                ('received_at', models.CharField(max_length=50)),
                ('station_id', models.CharField(max_length=50)),
                ('msg_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('turn', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ais_vessel_pos',
                'managed': False,
            },
        ),
    ]
