# Generated by Django 5.1.6 on 2025-04-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_aisdata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISVesselFiltered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.BigIntegerField()),
                ('received_at', models.DateTimeField()),
                ('status', models.IntegerField(null=True)),
                ('turn', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('course', models.FloatField(null=True)),
                ('heading', models.FloatField(null=True)),
                ('imo', models.BigIntegerField()),
                ('callsign', models.CharField(max_length=50)),
                ('shipname', models.CharField(max_length=100)),
                ('shiptype', models.IntegerField(null=True)),
                ('to_port', models.FloatField(null=True)),
                ('to_bow', models.FloatField(null=True)),
                ('to_stern', models.FloatField(null=True)),
                ('to_starboard', models.FloatField(null=True)),
                ('draught', models.FloatField(null=True)),
                ('destination', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='aisdata',
            table='ais_vessel_combo',
        ),
    ]
