# Generated by Django 5.1.6 on 2025-05-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_aisvesselfiltered_alter_aisdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipPhaseDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.BigIntegerField()),
                ('phase', models.CharField(max_length=32)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.FloatField()),
            ],
            options={
                'verbose_name': 'Ship Phase Duration',
                'verbose_name_plural': 'Ship Phase Durations',
                'db_table': 'ship_phase_duration',
            },
        ),
        migrations.AlterModelOptions(
            name='aisvesselfiltered',
            options={'managed': False},
        ),
    ]
