# Generated by Django 5.2.1 on 2025-06-02 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_shipphaseduration_alter_aisvesselfiltered_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aisvesselfiltered',
            table='ais_vessel_filtered',
        ),
    ]
